spring.application.name=UserApplication
server.servlet.context-path=/
server.port=8082
server.servlet.session.timeout=15m
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/user_schema?useSSL=false
spring.datasource.username=newuser03
spring.datasource.password=newuser003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
# SSL/mTLS Configuration
server.ssl.enabled=false
# Use 'need' to force the client to provide a certificate
#server.ssl.client-auth=need
# Key Store (The server's identity)
server.ssl.key-store=classpath:auth-service/auth.p12
server.ssl.key-store-password=macbook2019
server.ssl.key-store-type=PKCS12
# Trust Store (Who the server trusts)
server.ssl.trust-store=classpath:auth-service/truststore.jks
server.ssl.trust-store-password=macbook2019
# rsa key pair decryption purpose
rsa-private-key.path=/Users/user/.openssl/auth260222.pem