changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/publiclink-db?useSSL=false&serverTimezone=UTC 
zone=UTC
username=root
password=Formysql
verbose=true
dropFirst=false

# Logging
logLevel=info
classpath=target/classess

# Optional
defaultSchemaName=publiclink-db