server.port=8080
# WebFlux Configuration (Reactive, Non-blocking)
server.netty.connection-timeout=60000
# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
# Authentication service (SSL/mTLS Configuration)
server.ssl.enabled=false
# Use 'need' to force the client to provide a certificate
#server.ssl.client-auth=need
# Trust Store (Who the server trusts)
server.ssl.key-store=classpath:auth-service/gateway.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=macbook2019
server.ssl.trust-store=classpath:auth-service/truststore.jks
server.ssl.trust-store-password=macbook2019
# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.connection-timeout=5000
# Publisher confirms and returns
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# Template settings
spring.rabbitmq.template.mandatory=true
spring.config.import=classpath:ratelimiter/ratelimiter.yml
# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
# JWT configuration
jwt.secret=${JWT_KEY}
jwt.expiration=3600000
jwt.refresh-expiration=86400000
# Logging
logging.level.com.example.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
rsa-private-key.path=/Users/user/.openssl/auth260222.pem
rsa-pubkey.path=/Users/user/.openssl/pubauth.pem
spring.main.allow-bean-definition-overriding=true