server.port=8080
# application.properties
logging.level.org.apache.tomcat=DEBUG
logging.level.org.apache.catalina=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
# authentication service
# SSL/mTLS Configuration
server.ssl.enabled=false
# Use 'need' to force the client to provide a certificate
#server.ssl.client-auth=need
# Trust Store (Who the server trusts)
server.ssl.key-store=classpath:auth-service/gateway.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=macbook2019
server.ssl.trust-store=classpath:auth-service/truststore.jks
server.ssl.trust-store-password=macbook2019
# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.connection-timeout=5000
# Publisher confirms and returns
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# Template settings
spring.rabbitmq.template.mandatory=true
