spring.profiles.active=dev
spring.profiles.default=dev
spring.application.name=PublicLinkApplication
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
# WebFlux Configuration (Reactive, Non-blocking)
server.netty.connection-timeout=60000
# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
# Authentication service (SSL/mTLS Configuration)
server.ssl.enabled=false
# Use 'need' to force the client to provide a certificate
#server.ssl.client-auth=need
# Key Store (The server's identity)
server.ssl.key-store=classpath:auth-service/auth.p12
server.ssl.key-store-password=macbook2019
server.ssl.key-store-type=PKCS12
# Trust Store (Who the server trusts)
server.ssl.trust-store=classpath:auth-service/truststore.jks
server.ssl.trust-store-password=macbook2019
# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.connection-timeout=5000
# Template settings
spring.rabbitmq.template.mandatory=true
# Listener settings for simple container
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.retry.enabled=false
spring.rabbitmq.listener.simple.default-requeue-rejected=false
jwt.secret=${JWT_KEY}
jwt.secret.url=${JWT_URLKEY}
jwt.url.expired=172800000
link.auth.expired=36000000

# External service URLs
user.service.url=http://localhost:8082
security.service.url=http://localhost:8080
