spring.webflux.base-path=/publiclink
server.port=9080
server.address=0.0.0.0
#server.servlet.context-path=/publiclink
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/publiclink-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Formysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml