application.name=AuthenticationAuthorisationApplication
server.servlet.context-path=/authen-authorisation
server.port=8081
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/publiclink-db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=newuser02
spring.datasource.password=newuser002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=${JWT_KEY}
jwt.secret.url=${JWT_URLKEY}
jwt.url.expired=172800000
# rsa key pair
key.path=/Users/user/.openssl/auth260222.pem
pubkey.path=/Users/user/.openssl/pubauth.pem